### ISSUE TITLE
Empty window

### ISSUE THREAD

**Issue by shimizu-izumi** [WarningImHack3r/intellij-shadcn-plugin#45] opened 2024-06-07 09:19 UTC
### What is the issue?

The plugin window inside the IDE is empty but I have a valid components.json file
![image](https://github.com/WarningImHack3r/intellij-shadcn-plugin/assets/53613583/ae429aee-7df9-4edb-8802-c703cf85ccbf)

### What are the steps to reproduce this issue?

Setup a Next.js project with shadncn/ui, install the plugin, open the plugin window

### What were you expecting to happen?

The window content should be what is seen on the plugin screenshots

### What OS are you experiencing the problem on?

Windows

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment] 2024-06-07 12:01
Hi there, sorry for the inconvenience. Can you please send me the logs? To do so:
1. Enable my plugin's debug logs by setting the line below in `Help > Diagnostic Tools > Debug Log Settings…`:
  ```
  #com.github.warningimhack3r.intellijshadcnplugin
  ```
2. Restart your IDE, wait until your problem occurs and open the `idea.log` file you find by going to `Help > Show Log in Explorer`
3. In there, if you can send me the 50-ish lines before the end, I could try to diagnose your issue more precisely!

**Comment by WarningImHack3r** [comment] 2024-06-07 12:36
An empty window without crash is weird though, are you sure the plugin didn't (silently) crash? You can check that in the bottom right corner of the IDE in the bell icon (alert icon with your theme I guess)

**Comment by shimizu-izumi** [comment] 2024-06-07 14:04
It did crash silently while trying to read my tsconfig.json

**Comment by WarningImHack3r** [comment] 2024-06-07 14:27
Oh then that seems a duplicate of #32, can you try removing comments temporarily from your `tsconfig.json`, reopening the IDE and see if you still got the issue?

**Comment by shimizu-izumi** [comment] 2024-06-07 14:36
That fixed the problem

**Comment by shimizu-izumi** [comment] 2024-06-07 14:37
Duplicate of https://github.com/WarningImHack3r/intellij-shadcn-plugin/issues/32

**Closed** 2024-06-07 14:39 UTC
Labels: bug
