### ISSUE TITLE
[crash] Unhandled exception in Dispatchers.Default

### ISSUE THREAD

**Issue by Keloran** [WarningImHack3r/intellij-shadcn-plugin#68] opened 2024-11-06 00:58 UTC
### What is the issue?

this is my json

```
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/styles/globals.css",
    "baseColor": "stone",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "~/components",
    "utils": "~/lib/utils",
    "hooks": "~/hooks",
    "lib": "~/lib"
  }
}
```

### What are the steps to reproduce this issue?

just opening the tool window

### What were you expecting to happen?

expected it to show the components i have installed

### Paste any relevant logs, error output, etc.

```shell
com.github.warningimhack3r.intellijshadcnplugin.backend.sources.UnparseableConfigException: Unable to parse components.json
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoro

<TRIMMED STACKTRACE>
```

### What OS are you experiencing the problem on?

Linux

### Additional platform information

Build version: WebStorm 2024.2.4 Build: #WS-242.23726.96 October 22, 2024
JRE: 21.0.4+13-b509.26, JetBrains s.r.o.
JVM: 21.0.4+13-b509.26, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.11.5-arch1-1 (amd64)
_JAVA_OPTIONS=-Djava.util.prefs.userRoot="/home/keloran/.config/java"

=== Plugins ===
Custom plugins: [Supermaven (1.42), Code Note : Project Notes, Visual Markdown Editor (2024.2.2), Indent Rainbow (2.2.0), WakaTime (15.0.3), Kubernetes (242.23726.19), .env files support (2024.2.1), shadcn/ui Components Manager (0.9.3), GitHub Copilot (1.5.28.7313), Dracula Pro (1.4.0), Rainbow Brackets (2024.2.6-241)]
Disabled plugins:[]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment] 2024-11-06 06:11
It looks like you’re using the CLI 2.0, it’s not support yet as you can see on the other open issue. Please reopen if you figure out it’s not that!

Duplicate of #60

**Closed** 2024-11-06 06:12 UTC
Labels: bug
