### ISSUE TITLE
[crash] Unhandled exception in Dispatchers.Default

### ISSUE THREAD

**Issue by Luna5akura** [WarningImHack3r/intellij-shadcn-plugin#50] opened 2024-06-21 07:16 UTC
### What is the issue?

can't open in the edition 2024.2 EAP

### What are the steps to reproduce this issue?

just can't open

### What were you expecting to happen?

just can't open

### Paste any relevant logs, error output, etc.

```shell
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 393: Expected colon ':', but had ',' instead at path: $
JSON input: ....."next"
}
],
"paths": {
"@*.ts", "***.ts"],
"exclude": ["node.....
	at com.github.warningimhack3r.intellijshadcnplugin.backend.sources.Source.parseTsConfig(Source.kt:120)
	at com.github.warningimhack3r.intellijshadcnplugin.backend.sources.impl.ReactSource.resolveAlias(ReactSource.kt:42)
	at com.github.warningimhack3r.intellijshadcnplugin.backend.sources.Source.getInstalledComponents(Source.kt:154)
	at com.github.warningimhack3r.intellijshadcnplugin.ui.ISPWindowContents$panel$1$1.invokeSuspend(ISPWindowContents.kt:54)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@47f99218, Dispatchers.Default]
```

### What OS are you experiencing the problem on?

Windows

### Additional platform information

Build version: WebStorm 2024.2 EAP Build: #WS-242.16677.27 June 14, 2024
JRE: 21.0.3+13-b480.1, JetBrains s.r.o.
JVM: 21.0.3+13-b480.1, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Windows 11.0 (amd64)

=== Plugins ===
Custom plugins: [IdeaVim (2.12.0), TeXiFy IDEA (0.9.6), PDF Viewer (0.15.0), WakaTime (14.3.15), Markdown Editor (2.0.5), CMD Support (1.0.5), Easy-Translation (2.01.01), React snippets (1.1.1), SciaReto Mind Map (1.6.7), Batch Scripts Support (1.0.13), .env files support (2024.2), Prisma ORM (242.16677.12), Rainbow Brackets (2024.2.4-241), shadcn/ui Components Manager (0.8.3)]
Disabled plugins:[R Language for IntelliJ (241.14494.158), CodeGeeX (2.9.0-223), GitToolBox (500.2.9+233)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment] 2024-06-21 08:26
Duplicate of #48, fixed in 0.8.4 which should be out in less than 48h. Sorry for the inconvenience!

**Closed** 2024-06-21 08:26 UTC
Labels: bug

**Comment by WarningImHack3r** [comment] 2024-06-21 08:27
It's fixed in 0.8.4 which should be out in less than 48h. Sorry for the inconvenience!

**Comment by WarningImHack3r** [comment] 2024-06-21 18:13
@Luna5akura the update is live!

**Comment by Luna5akura** [comment] 2024-07-03 15:53
ty sorry i didn't see it
